import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pagePath } from "../shared/urls.mjs";

// Site search runs entirely in the browser from this build-time index, so no search service is needed.

const decode = value => String(value)
  .replace(/<[^>]+>/g, " ")
  .replace(/&amp;/g, "&").replace(/&(?:#39|rsquo|lsquo|apos);/g, "'").replace(/&(?:ldquo|rdquo|quot);/g, '"').replace(/&nbsp;/g, " ").replace(/&#8594;|&#8599;/g, "")
  .replace(/\s+/g, " ").trim();
const clip = (value, length = 150) => value.length > length ? `${value.slice(0, length).replace(/\s+\S*$/, "")}\u2026` : value;

export function pageKind(page) {
  if (page === "index.html") return "Home";
  if (["services.html", "security.html", "ai-business.html", "cloud-platforms.html"].includes(page)) return "Service";
  if (page === "industries.html" || page.startsWith("industry-")) return "Industry";
  if (page.startsWith("deep-dive-") || page === "technology-deep-dives.html") return "Deep dive";
  if (page.startsWith("insight-") || page === "perspectives.html") return "Perspective";
  if (page.startsWith("scenario-") || page === "solutions-in-practice.html") return "Example";
  if (page.startsWith("brief-") || page === "briefs.html") return "Service brief";
  if (page === "faq.html") return "FAQ";
  if (page === "sources.html") return "Product";
  return "Page";
}

export function searchEntries(page, html) {
  if (page === "404.html" || /id="(?:resource|insights)-destination"/.test(html)) return [];
  const route = pagePath(page);
  const title = decode(html.match(/<h1(?:\s[^>]*)?>([\s\S]*?)<\/h1>/)?.[1] || html.match(/<title>([^<|]+)/)?.[1] || page);
  const description = decode(html.match(/<meta name="description" content="([^"]*)"/)?.[1] || "");
  const main = html.match(/<main\b[\s\S]*?<\/main>/)?.[0] || "";
  const headings = [...main.matchAll(/<h[23][^>]*>([\s\S]*?)<\/h[23]>/g)].map(match => decode(match[1])).filter(Boolean).slice(0, 24).join(" ");
  const kind = pageKind(page);
  const entries = [{ t: title, u: route, k: kind, d: clip(description), w: headings }];
  const industry = page.startsWith("industry-") ? title : "";
  for (const match of main.matchAll(/<section class="practice" id="([^"]+)"[\s\S]*?<p class="eyebrow">([\s\S]*?)<\/p>[\s\S]*?<h2[^>]*>([\s\S]*?)<\/h2>(?:\s*<p>([\s\S]*?)<\/p>)?/g)) {
    entries.push({ t: decode(match[2]), u: `${route}#${match[1]}`, k: "Capability", d: clip(decode(match[3])), w: decode(match[4] || "") });
  }
  for (const match of main.matchAll(/<article class="use-case[^"]*" id="([^"]+)"[^>]*>\s*<p class="eyebrow">([\s\S]*?)<\/p>\s*<h2[^>]*>([\s\S]*?)<\/h2>(?:\s*<p class="use-case-challenge">([\s\S]*?)<\/p>)?/g)) {
    entries.push({ t: decode(match[3]), u: `${route}#${match[1]}`, k: `${industry} use case`, d: clip(decode(match[4] || "")), w: decode(match[2]) });
  }
  for (const match of main.matchAll(/<article class="source-entry product-entry" id="([^"]+)">[\s\S]*?<h3>([\s\S]*?)<\/h3>\s*<p><strong>The problem:<\/strong>([\s\S]*?)<\/p>/g)) {
    entries.push({ t: decode(match[2]), u: `${route}#${match[1]}`, k: "Product", d: clip(decode(match[3])), w: "" });
  }
  for (const group of main.matchAll(/<section class="faq-group" id="([^"]+)"[\s\S]*?<\/section>/g)) {
    for (const question of group[0].matchAll(/<summary>([\s\S]*?)<\/summary>\s*<div>([\s\S]*?)<\/div>/g)) {
      entries.push({ t: decode(question[1]), u: `${route}#${group[1]}`, k: "Question", d: clip(decode(question[2])), w: "" });
    }
  }
  return entries;
}

export async function syncSearchIndex(root) {
  const site = path.join(root, "src", "site");
  const pages = (await readdir(site)).filter(name => name.endsWith(".html")).sort();
  const entries = [];
  for (const page of pages) entries.push(...searchEntries(page, await readFile(path.join(site, page), "utf8")));
  const body = `"use strict";\n// Generated by scripts/search-index.mjs. Do not edit by hand.\nwindow.cfcSearchIndex = ${JSON.stringify(entries)};\n`;
  const target = path.join(site, "assets", "search-index.js");
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== body) await writeFile(target, body);
  return entries.length;
}
